# -*- coding: utf-8 -*-
"""WatershedPooja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17VRZKOahTQV54rkWfo5CEfCI99dGc9fN
"""

from google.colab import drive
drive.mount('/content/gdrive')

import numpy as np
from skimage.segmentation import watershed,clear_border
import scipy.misc
import imageio # use im = imageio.imread(_____)
from matplotlib import pyplot as plt
import scipy.ndimage as ndi
import pickle
import os
from os import listdir
from skimage.feature import peak_local_max
from skimage.morphology import remove_small_objects,local_maxima,h_maxima
from skimage.measure import regionprops,label
import matplotlib.patches as mpatches

main_path='/content/gdrive/MyDrive/single_cell_segmentation-master'
ori_img_path=main_path+'/frcnn_predict'
img_list = sorted(listdir(ori_img_path))
print(img_list)
path_output=main_path+'/output'
mask_thres=0.2

with open(path_output+"/bndbox.txt", "rb") as fp: # Unpickling
    bndbox_traj= pickle.load(fp)
print(bndbox_traj)

